In [1]:
import torch
import numpy as np

In [2]:
action_n = 4
action_cog_n = 2
o_size = (3, 64, 64)

In [3]:
batch_size = 2
num_steps = 15

In [4]:
obs = torch.randint(action_cog_n, (batch_size, num_steps, 1))

In [5]:
a = torch.randint(action_n, (batch_size, num_steps, 1))

dones = torch.zeros((batch_size, num_steps, 1))
r = torch.rand((batch_size, num_steps, 1))

values_guess = torch.rand((batch_size, num_steps, 1))



In [6]:
a_cog = torch.randint(action_cog_n, (batch_size, num_steps, 1))


In [7]:
a_cog

tensor([[[0],
         [0],
         [1],
         [0],
         [1],
         [0],
         [1],
         [0],
         [0],
         [1],
         [0],
         [1],
         [1],
         [0],
         [0]],

        [[0],
         [1],
         [0],
         [1],
         [1],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0]]])

In [8]:
a

tensor([[[1],
         [3],
         [2],
         [1],
         [2],
         [0],
         [2],
         [1],
         [0],
         [1],
         [2],
         [1],
         [2],
         [3],
         [0]],

        [[3],
         [2],
         [3],
         [1],
         [2],
         [3],
         [3],
         [1],
         [1],
         [2],
         [0],
         [2],
         [3],
         [2],
         [3]]])

In [9]:
a[a_cog == 1] = 127

In [10]:
a

tensor([[[  1],
         [  3],
         [127],
         [  1],
         [127],
         [  0],
         [127],
         [  1],
         [  0],
         [127],
         [  2],
         [127],
         [127],
         [  3],
         [  0]],

        [[  3],
         [127],
         [  3],
         [127],
         [127],
         [  3],
         [  3],
         [  1],
         [  1],
         [  2],
         [  0],
         [  2],
         [  3],
         [  2],
         [  3]]])

In [11]:
a.shape

torch.Size([2, 15, 1])

In [12]:

(1 - a_cog) * a - 5*a_cog

tensor([[[ 1],
         [ 3],
         [-5],
         [ 1],
         [-5],
         [ 0],
         [-5],
         [ 1],
         [ 0],
         [-5],
         [ 2],
         [-5],
         [-5],
         [ 3],
         [ 0]],

        [[ 3],
         [-5],
         [ 3],
         [-5],
         [-5],
         [ 3],
         [ 3],
         [ 1],
         [ 1],
         [ 2],
         [ 0],
         [ 2],
         [ 3],
         [ 2],
         [ 3]]])

In [14]:
a_cog.shape

torch.Size([2, 15, 1])

In [15]:
a_cog = torch.randint(action_cog_n, (batch_size, 1))


In [16]:
a_cog

tensor([[1],
        [1]])

In [26]:
a_cog.expand(-1, )

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [30]:
a_cog.view((-1,) + 3*(1,)).expand(-1,-1,3,3)

tensor([[[[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]]],


        [[[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]]]])

In [32]:
a_cog.view(a_cog.size(0) + 3 * (1,)).expand(-1, -1, 3, 3)


TypeError: unsupported operand type(s) for +: 'int' and 'tuple'