In [1]:
import torch
import numpy as np

In [2]:
action_n = 4
action_cog_n = 2
o_size = (3, 64, 64)

In [3]:
batch_size = 2
num_steps = 15

In [4]:
obs = torch.randint(action_cog_n, (batch_size, num_steps, 1))

In [5]:
a = torch.randint(action_n, (batch_size, num_steps, 1))

dones = torch.zeros((batch_size, num_steps, 1))
r = torch.rand((batch_size, num_steps, 1))

values_guess = torch.rand((batch_size, num_steps, 1))



In [6]:
a_cog = torch.randint(action_cog_n, (batch_size, num_steps, 1))


In [10]:
a_cog

tensor([[[1],
         [1],
         [0],
         [0],
         [0],
         [1],
         [0],
         [0],
         [1],
         [0],
         [1],
         [0],
         [0],
         [1],
         [1]],

        [[1],
         [0],
         [0],
         [0],
         [0],
         [1],
         [0],
         [1],
         [1],
         [1],
         [1],
         [1],
         [0],
         [0],
         [0]]])

In [9]:
a

tensor([[[3],
         [2],
         [0],
         [2],
         [3],
         [1],
         [3],
         [1],
         [3],
         [3],
         [0],
         [1],
         [3],
         [3],
         [1]],

        [[0],
         [3],
         [1],
         [2],
         [0],
         [2],
         [3],
         [2],
         [3],
         [2],
         [3],
         [1],
         [1],
         [0],
         [2]]])

In [11]:
a[a_cog == 1] = 127

In [12]:
a

tensor([[[127],
         [127],
         [  0],
         [  2],
         [  3],
         [127],
         [  3],
         [  1],
         [127],
         [  3],
         [127],
         [  1],
         [  3],
         [127],
         [127]],

        [[127],
         [  3],
         [  1],
         [  2],
         [  0],
         [127],
         [  3],
         [127],
         [127],
         [127],
         [127],
         [127],
         [  1],
         [  0],
         [  2]]])

In [ ]:
a.shape

In [ ]:

(1 - a_cog) * a - 5*a_cog