In [4]:
import torch
from torch import nn

In [6]:
class CoordConv(nn.Module):
    def __init__(self, shape):
        super(CoordConv).__init__()
        self.shape = shape
        self.x = 
        

In [100]:
shape  = (6, 3)
x = torch.arange(0, 1, 1/shape[0])
x = x.view(1, 1, 1, -1)
x = x.expand(-1, -1, shape[1], shape[0])
y = torch.arange(0, 1, 1/shape[1])
y = y.view(1, 1, -1, 1)
y = y.expand(-1, -1, shape[1], shape[0])

coords = torch.cat((x,y), dim=1)
coords

tensor([[[[0.0000, 0.1667, 0.3333, 0.5000, 0.6667, 0.8333],
          [0.0000, 0.1667, 0.3333, 0.5000, 0.6667, 0.8333],
          [0.0000, 0.1667, 0.3333, 0.5000, 0.6667, 0.8333]],

         [[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.3333, 0.3333, 0.3333, 0.3333, 0.3333, 0.3333],
          [0.6667, 0.6667, 0.6667, 0.6667, 0.6667, 0.6667]]]])

In [72]:
torch.cat((x,y), dim=1)

tensor([[[[0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
          [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
          [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
          [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
          [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
          [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
          [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571]],

         [[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
          [0.2857, 0.2857, 0.2857, 0.2857, 0.2857, 0.2857, 0.2857],
          [0.4286, 0.4286, 0.4286, 0.4286, 0.4286, 0.4286, 0.4286],
          [0.5714, 0.5714, 0.5714, 0.5714, 0.5714, 0.5714, 0.5714],
          [0.7143, 0.7143, 0.7143, 0.7143, 0.7143, 0.7143, 0.7143],
          [0.8571, 0.8571, 0.8571, 0.8571, 0.8571, 0.8571, 0.8571]]]])

In [74]:
((x-0.5)**2 + (y-0.5)**2).sqrt()

tensor([[[[0.7071, 0.6145, 0.5440, 0.5051, 0.5051, 0.5440, 0.6145],
          [0.6145, 0.5051, 0.4165, 0.3642, 0.3642, 0.4165, 0.5051],
          [0.5440, 0.4165, 0.3030, 0.2259, 0.2259, 0.3030, 0.4165],
          [0.5051, 0.3642, 0.2259, 0.1010, 0.1010, 0.2259, 0.3642],
          [0.5051, 0.3642, 0.2259, 0.1010, 0.1010, 0.2259, 0.3642],
          [0.5440, 0.4165, 0.3030, 0.2259, 0.2259, 0.3030, 0.4165],
          [0.6145, 0.5051, 0.4165, 0.3642, 0.3642, 0.4165, 0.5051]]]])

In [76]:
type(())

tuple

In [84]:
x.expand(2, -1, -1, -1).expand(-1, -1, -1, -1)

tensor([[[[0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
          [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
          [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
          [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
          [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
          [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
          [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571]]],


        [[[0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
          [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
          [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
          [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
          [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
          [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
          [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571]]]])