In [1]:
import matplotlib.pyplot as plt
import numpy as np
import torch
import gym

In [2]:
from hydra.experimental import compose, initialize
initialize(
    config_path="../configs",
)

In [3]:
import rl_trickery.envs
import rl_trickery.utils.utils as utils
from rl_trickery.utils.logger import Logger
from rl_trickery.utils.video import VideoRecorder
from rl_trickery.envs import make_envs

In [4]:
cfg = compose("simple")
print(cfg.pretty())

num_timesteps: 1000000.0
device: cuda:0
seed: 1
num_envs: ${agent.num_envs}
log_frequency_step: 1
log_save_tb: true
save_video: true
eval_frequency_step: 500
num_eval_episodes: 8
env:
  env_id: FrozenLake-v0
  env_kwargs: {}
  max_timesteps: 100
  obs_type: proprioceptive
  image_size: 64
  to_grayscale: false
  episode_life: false
  clip_rewards: false
  mind_pause: false
  frame_stack: 1
  frame_skip: 1
  random_initial_steps: 0
  pytorch_dim_order: true
  device: ${device}
agent:
  name: a2c
  num_envs: 8
  num_steps: 5
  device: ${device}
  network_params:
    architecture: rnn
    state_channels: 32
    hidden_size: 64
  algo_params:
    lr: 0.001
    gamma: 0.99
    value_loss_coef: 0.5
    entropy_coef: 0.01
    eps: 1.0e-05
    alpha: 0.99
    max_grad_norm: 0.1
    use_timeout: true
    optimizer_type: rmsprop



In [5]:
env = make_envs(
    **cfg.env,
    seed=cfg.seed,
    num_envs=cfg.num_envs,
)

In [13]:
env.observation_space.__class__.__name__

'Discrete'

In [8]:
env.reset()

tensor([[-0.0440,  0.0027, -0.0460,  0.0478]], device='cuda:0')

In [7]:
s = env.reset()
plt.imshow(s[0].cpu().numpy().transpose(1, 2, 0))

ValueError: axes don't match array

In [40]:
a = torch.LongTensor([0, 2, 5])
b = torch.zeros((3, 6))
b[range(a.size(0)), a] = 1

In [41]:
b

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [37]:
b.shape

torch.Size([3, 6])

In [39]:
b

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1.]])

## Generate fixed mazes

In [ ]:
import numpy as np

In [ ]:
from rl_trickery.envs.maze import Maze

In [ ]:
goal = np.unravel_index(np.argmin(m.board, axis=None), m.board.shape)

In [ ]:
np.atleast_2d(goal)

In [ ]:
%cd ../rl_trickery/envs/

In [ ]:
for k in range(4, 65):
    m  = Maze("maze", k)
    np.save("raw_maze_{}".format(k), m.board)

In [ ]:
xxxx

In [ ]:
import pkg_resources

In [ ]:
np.load(pkg_resources.resource_filename("rl_trickery", "envs/mazes/raw_maze_12.npy"))