In [1]:
from rl_trickery.models.conv_lstm import ConvLSTM, ConvLSTMCell

In [17]:
net = ConvLSTMCell(32, 32, (3,3), True)

In [11]:
from rl_trickery.utils.utils import get_n_params

In [3]:
import torch

In [4]:
a = torch.zeros(1, 32, 7, 7)

In [5]:
a.shape[0]

1

In [9]:
net(a, None)[0].shape

torch.Size([1, 16, 7, 7])

In [18]:
get_n_params(net)

73856

In [7]:
for i in range(-1):
    print(i)

In [21]:

a = torch.FloatTensor([[[[1.0]]]])

In [33]:
a.squeeze().dim()

0

In [36]:
a = torch.rand(5,5)

In [38]:
a

tensor([[0.0024, 0.5946, 0.2140, 0.8817, 0.4150],
        [0.1377, 0.7281, 0.6948, 0.8506, 0.0372],
        [0.9338, 0.3816, 0.5067, 0.2769, 0.4962],
        [0.9227, 0.5486, 0.0743, 0.8943, 0.8816],
        [0.6332, 0.0461, 0.5191, 0.8641, 0.6956]])

In [43]:
a = torch.rand(16, 512)
b = torch.rand(16)

In [46]:
a * b.view(-1, 1)

tensor([[0.0533, 0.0757, 0.0376,  ..., 0.0629, 0.2578, 0.2234],
        [0.1364, 0.6984, 0.4953,  ..., 0.7105, 0.6586, 0.4684],
        [0.0824, 0.0483, 0.0771,  ..., 0.0235, 0.1081, 0.0456],
        ...,
        [0.0251, 0.0163, 0.0048,  ..., 0.0365, 0.0133, 0.0274],
        [0.0508, 0.0379, 0.0362,  ..., 0.0108, 0.0107, 0.0046],
        [0.2611, 0.0570, 0.2519,  ..., 0.0011, 0.2760, 0.0096]])

In [47]:
a.view(-1, -1)

RuntimeError: only one dimension can be inferred

In [48]:
import numpy as np

In [52]:
a

tensor([[0.1980, 0.2809, 0.1395,  ..., 0.2333, 0.9566, 0.8292],
        [0.1798, 0.9208, 0.6531,  ..., 0.9369, 0.8684, 0.6177],
        [0.5745, 0.3368, 0.5371,  ..., 0.1638, 0.7533, 0.3181],
        ...,
        [0.5128, 0.3327, 0.0979,  ..., 0.7447, 0.2705, 0.5594],
        [0.7966, 0.5942, 0.5676,  ..., 0.1692, 0.1680, 0.0723],
        [0.9371, 0.2047, 0.9042,  ..., 0.0040, 0.9905, 0.0346]])

In [69]:
b.view(-1, *(5*(1,))).shape

torch.Size([16, 1, 1, 1, 1, 1])

In [51]:
np.atleast_1d(1)

SyntaxError: can't use starred expression here (<ipython-input-51-b14d2d09c62e>, line 1)